### PR TITLE
Header attribute replacement, similar to anchor attribute injection

### PR DESCRIPTION
**Pull request by GriceTurrble**
~~When using this script, Bootstrap TOC plugin (https://afeld.github.io/bootstrap-toc/) will include the anchor text in its output.
This change allows setting a `bootstrapToc` parameter that adjusts the new header tag, adding a `data-toc-text` attr with the `heading` text.
That attr tells Bootstrap TOC to use that text for its output, not the full contents of the tag.~~

Edit: based on comment from @allejo , changing to a more generic version to inject header attributes with replacement features.

Mainly interested in putting the original heading text into, for example, `data-toc-text` for using Bootstrap TOC plugin, so the use case is somewhat minimal; but in providing ability to add a dynamic header attrs that can exclude the anchor text automatically, this helps write posts with simpler markup for that use case (and any other case someone may come across with a similar need).

### CODE REVIEW

**Comment by allejo** [comment]
Doing it like this, it would be _way_ too specialized to just Bootstrap TOC. This project is entirely separate from Bootstrap TOC so it shouldn't have any special features for it.

A better way of doing this would be to add a `headerAttrs` parameter (similar to `anchorAttrs`) and allow for a `%heading%` placeholder.

Additionally, this type of new feature would require some unit tests too!

**Comment by GriceTurrble** [comment]
Alright, fair point on making a generic version. Tested in my local site, seems to be working. And added tests in the style of the `anchorAttrs` placeholder tests.

**Comment by GriceTurrble** [comment]
Tweaks completed. 😁 Let me know what you think!

**Review by allejo — APPROVED** [review]

**Comment by allejo** [comment]
Looks great! Thanks @GriceTurrble! :smile:

**Pull request merged**
